### ISSUE TITLE
[Request] Floating top bar

### ISSUE THREAD

**Issue by tac1ica** [jthingelstad/foreground#312]
Will you please consider adding an option that makes the top bar stay always on view when scrolling down the page.

Thanks.

**Comment by Hutchy68** [comment]
I look into it but there are a couple things going on with a fixed class on the navbar. Mainly, the div of the navbar becomes ignored and the whole page shifts up by the height of the navbar plus the margin below the navbar since it becomes ignored. This hides some of the main page display. Making it an option isn't easy as true/false as it would require some CSS changes based on the option being set to true.

**Comment by Hutchy68** [comment]
>Will you please consider adding an option that makes the top bar stay always on view when scrolling down the page.

Already possible with `'NavWrapperType' => 'contain-to-grid fixed'` in LocalSettings skin options.
