### ISSUE TITLE
MW 1.35 compatibility

### ISSUE THREAD

**Issue by rebastion** [jthingelstad/foreground#375]
Hi there. Not an actual issue as such, but since the release notes for the upcoming long-term-support release of MW state "Both the Vector skin and the underlying skin infrastructure are undergoing numerous changes, so there might be things broken that are
already fixed in master and as such need backporting." and the PHP requirements have been raised etc, I am wondering if Foreground will work flawlessly out of the box for this new release (which I will use as an excuse for some major upgrades on my wikis) or if I should hold off until you good folks give the OK sign :)

**Comment by samwilson** [comment]
I'm not a maintainer here, but Foreground is mostly working in my local dev site which is on 1.35. The only issue I've found is #373. (That doesn't mean there aren't other issues of course!)

**Comment by rebastion** [comment]
So I upgraded, and no images are aligning properly anymore. First I thought it was an issue with MW, see here:

https://www.mediawiki.org/wiki/Topic:Vwfv9zth6s7fghow

**Comment by dhowland** [comment]
Is this project abandoned?  Looks like there hasn't been any updates since Jan 2020 and 1.35 comparability is important.

**Comment by Hutchy68** [comment]
No, it’s not abandoned. If you have a pull request please submit one.

**Comment by dhowland** [comment]
Looks like @samwilson submitted his on Aug 26.

I ask because I just installed Foreground on a fresh 1.35 install and it seems.... not right.

**Comment by rebastion** [comment]
Yea it could probably do with an overhaul :)

**Comment by Hutchy68** [comment]
I am looking at a fresh MW 1.35 with the 2.3.0 and everything looks ok with the exception of the core css being ripped out. The only mention in MW changelog... "The "mediawiki.legacy.oldshared" module has been deprecated. Skins and extensions that are using this should copy its necessary CSS rules to their own styles module. CologneBlue and Nostalgia skins serve as examples."

This amounts to them creating a legacy css file to load called `oldshared.css`. Stumps me as using left or right in the image wiki text should be a responsibility of MW to make sure the image does what is expected of it to do, float left or right.

>Looks like @samwilson submitted his on Aug 26.

This only handles deprecated methods, they are still available in 1.35 and won't be removed until 1.36. Not critical but will be needed, thanks @samwilson. They just need to be tested that nothing breaks.

A couple more things I noticed. Category links at bottom are not floating and have a `list-style: none;` and the menu hamburger disappears in iOS14, I thing because of box-shadow which is a common use to create the hamburger icons.

The bigger question is what to do about the general appearance. It probably looks odd to @dhowland because on a full screen the headings a large.

- Should we pull in the oldshared, rewrite the whole foreground.css stylesheet or post here is how you fix it, use common.css or foreground.css in the `MediaWiki:` sense. 
- Make patches to what is current to focus time on moving everything to Foundation for Sites 6.

**Comment by dhowland** [comment]
Perhaps I should create my own issue.  I'm new at this, and I just figured that there might be a compatibility issue with 1.35, which is how I found this existing thread.

Like I said, it's a fresh install.  [This is vector](https://i.imgur.com/E2A2qVx.png), [this is foreground](https://i.imgur.com/S3uxsqH.png).

The edit links are very large, new text has shown up that is only supposed to be for print jobs (the tagline and the "retrieved from" footer), there is an empty box around a div at the bottom, which I assume would be for categories, if there were any.  Also the icon is missing from "Edit".

Again, I'm new at this, I don't know how it's really supposed to look.

**Comment by Hutchy68** [comment]
Pull down the latest branch of develop and see if that corrects a lot of the formatting issues. PR #380 - I added in the legacy.css of core which loaded automatically for all skins. Should have fixed everything to what Foreground looked like for MW < 1.35

**Comment by Hutchy68** [comment]
Closing, Foreground is compatible on the develop branch now.
